service: worlds-worst-text-adventures

provider:
  name: aws
  region: us-east-1
  runtime: python3.7

functions:
  text_adventure:
    handler: text_adventure.do_action
    timeout: 30
    events:
      - http:
          path: route
          method: post
          cors: true

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

package:
  exclude:
    - node_modules/**
    - venv/**